### ISSUE TITLE
Publish this repo's readme as a standalone blog post

### ISSUE THREAD

**Issue by ummahusla** [Daniel-GabrielN/CoreMigrationsWebApi#1]
Might be a good idea to publish it to the resources like **[Medium](http://medium.com/)** or personal blog post.

**Comment by ummahusla** [comment]
@Daniel-GabrielN Any updates?

**Comment by Daniel-GabrielN** [comment]
@ummahusla Thank you for the suggestion, this is not a priority right now, will do it at some point in the future.
